## Acertijo: ¿Cuál es el siguiente número en esta lista?


¿Cuál es el siguiente número en esta lista?:
4, 6, 12, 18, 30, 42, 60, 72, 102, 108, 138, ..


## Números primos

In [46]:
def is_prime(n):
    return all(n%j for j in range(2,n))*(n>1)


for x in range(20):
    print(x, ':', True if is_prime(x) else False)

0 : False
1 : False
2 : True
3 : True
4 : False
5 : True
6 : False
7 : True
8 : False
9 : False
10 : False
11 : True
12 : False
13 : True
14 : False
15 : False
16 : False
17 : True
18 : False
19 : True


## Primos gemelos

https://en.wikipedia.org/wiki/Twin_prime

Hay algunos números primos que vienen por parejas, separados por un único número. El 3 y el 5 por ejemplo. Ahora bien, ¿hay infinitas de estas parejas? Esta pregunta tiene nombre, es la [conjetura de los números primos gemelos](https://es.wikipedia.org/wiki/Conjetura_de_los_n%C3%BAmeros_primos_gemelos) y es un caso concreto de la [conjetura de Polignac](https://en.wikipedia.org/wiki/Polignac%27s_conjecture)





In [48]:
twin_primes = []

last_prime = 1
for x in range(10000):
    if is_prime(x):
        if x - last_prime == 2:
            twin_primes.append((last_prime, x))
        last_prime = x

twin_primes[:10] #first 10

[(3, 5),
 (5, 7),
 (11, 13),
 (17, 19),
 (29, 31),
 (41, 43),
 (59, 61),
 (71, 73),
 (101, 103),
 (107, 109)]

## Conjetura de Goldbach

https://es.wikipedia.org/wiki/Conjetura_de_Goldbach


> Todo número par mayor que 2 puede escribirse como suma de dos números primos. Christian Goldbach (1742)


Ejemplos:
$
4 = 1+3 \\
8 = 3+5 \\
24 = 13+11 \\
52 = 23+29$

## Solución acertijo: Average of twin prime pairs

¿Cuál es el siguiente número en esta lista?:
4, 6, 12, 18, 30, 42, 60, 72, 102, 108, 138, ..

Más info aquí: http://oeis.org/A014574


In [49]:
av_twins = [a+1 for (a, b) in twin_primes]

av_twins[:10] #first 10

[4, 6, 12, 18, 30, 42, 60, 72, 102, 108]

## ¿Un caso especial de la Conjetura de Goldbach?

Todos los números en la lista anterior 4, 6, 12, 18, 30, 42, 60, 72, 102, 108, 138, ... parecen poder escribirse como suma de dos números anteriores en la lista. 

Ejemplos: 
$ 
18 = 12 + 6 \\
30 = 12 + 18 \\
42 = 30 + 12 \\
...
$

Podemos ver que esto ocurre, al menos, para todos los números primos gemelos menores que 100.000:

In [41]:
for i in range(len(av_twins)):
    N = av_twins[i]
    print(i, N, N in [a + b for a in av_twins[:i] for b in av_twins[:i]])

0 4 False
1 6 False
2 12 True
3 18 True
4 30 True
5 42 True
6 60 True
7 72 True
8 102 True
9 108 True
10 138 True
11 150 True
12 180 True
13 192 True
14 198 True
15 228 True
16 240 True
17 270 True
18 282 True
19 312 True
20 348 True
21 420 True
22 432 True
23 462 True
24 522 True
25 570 True
26 600 True
27 618 True
28 642 True
29 660 True
30 810 True
31 822 True
32 828 True
33 858 True
34 882 True
35 1020 True
36 1032 True
37 1050 True
38 1062 True
39 1092 True
40 1152 True
41 1230 True
42 1278 True
43 1290 True
44 1302 True
45 1320 True
46 1428 True
47 1452 True
48 1482 True
49 1488 True
50 1608 True
51 1620 True
52 1668 True
53 1698 True
54 1722 True
55 1788 True
56 1872 True
57 1878 True
58 1932 True
59 1950 True
60 1998 True
61 2028 True
62 2082 True
63 2088 True
64 2112 True
65 2130 True
66 2142 True
67 2238 True
68 2268 True
69 2310 True
70 2340 True
71 2382 True
72 2550 True
73 2592 True
74 2658 True
75 2688 True
76 2712 True
77 2730 True
78 2790 True
79 2802 True
80 2970 True


572 38328 True
573 38448 True
574 38460 True
575 38568 True
576 38610 True
577 38652 True
578 38670 True
579 38712 True
580 38748 True
581 38922 True
582 39042 True
583 39162 True
584 39228 True
585 39240 True
586 39342 True
587 39372 True
588 39510 True
589 39828 True
590 39840 True
591 40038 True
592 40128 True
593 40152 True
594 40428 True
595 40530 True
596 40638 True
597 40698 True
598 40848 True
599 41142 True
600 41178 True
601 41202 True
602 41232 True
603 41388 True
604 41412 True
605 41520 True
606 41610 True
607 41760 True
608 41850 True
609 41958 True
610 41982 True
611 42018 True
612 42072 True
613 42180 True
614 42222 True
615 42282 True
616 42408 True
617 42462 True
618 42570 True
619 42642 True
620 42702 True
621 42840 True
622 42900 True
623 43050 True
624 43320 True
625 43398 True
626 43542 True
627 43578 True
628 43608 True
629 43650 True
630 43782 True
631 43788 True
632 43890 True
633 43962 True
634 44028 True
635 44088 True
636 44130 True
637 44202 True
638 44268 

1113 89670 True
1114 89820 True
1115 89898 True
1116 90018 True
1117 90072 True
1118 90198 True
1119 90372 True
1120 90402 True
1121 90438 True
1122 90528 True
1123 90618 True
1124 90678 True
1125 90822 True
1126 91080 True
1127 91098 True
1128 91128 True
1129 91140 True
1130 91152 True
1131 91368 True
1132 91458 True
1133 91572 True
1134 91812 True
1135 91968 True
1136 92178 True
1137 92220 True
1138 92382 True
1139 92400 True
1140 92460 True
1141 92568 True
1142 92640 True
1143 92670 True
1144 92682 True
1145 92790 True
1146 92862 True
1147 92958 True
1148 93132 True
1149 93240 True
1150 93252 True
1151 93282 True
1152 93480 True
1153 93492 True
1154 93558 True
1155 93702 True
1156 93762 True
1157 93810 True
1158 93888 True
1159 93912 True
1160 94008 True
1161 94110 True
1162 94152 True
1163 94308 True
1164 94350 True
1165 94398 True
1166 94440 True
1167 94530 True
1168 94542 True
1169 94560 True
1170 94650 True
1171 94848 True
1172 94950 True
1173 95088 True
1174 95190 True
1175 952

Esto guarda una curiosa relación con la conjetura de Goldbach ya que si un número de esa lista puede escribirse como suma de dos números anteriores en la lista, entonces también puede escribirse de forma directa como suma de dos primos.. de dos maneras distintas!

$ 30 = 12 + 18 \\
30 = 11 + 19 \ (primos) \\
30 = 13 + 21 \ (primos)
$

Todo número que es media de dos primos gemelos (como el 30) es par, y por la conjetura de Goldbach ya "sabíamos" que puede ser escrito como suma de dos números primos. Pero... ¿son además esos dos números primos siempre parte de la lista de primos gemelos?